require('dotenv').config()
const CONFIG = {}
CONFIG.MONGOURL=process.env.MONGOURL
CONFIG.PORT = process.env.PORT
CONFIG.EMALKHANADOC = process.env.EMALKHANADOC
CONFIG.REOPENUPLOADORDERDOC = process.env.REOPENUPLOADORDERDOC
CONFIG.BARCODEFILE = process.env.BARCODEFILE
CONFIG.ACCESS_KEY = process.env.ACCESS_KEY
CONFIG.SECRET_KEY = process.env.SECRET_KEY
CONFIG.BUCKET_NAME = process.env.BUCKET_NAME
CONFIG.EMALKHANANO = process.env.EMALKHANANO;
CONFIG.REGION = process.env.REGION;

module.exports = CONFIG;
